preserve_hierarchy: 1
files:
  - source: config/locales/en.yml
    translation: config/locales/%two_letters_code%.yml
    update_option: update_as_unapproved
pull_request_title: Crowdin translations
pull_request_labels:
  - ikigai
commit_message: New translations %original_file_name% from Crowdin
append_commit_message: 
pull_request_assignees:
  - anushka123123456789
