preserve_hierarchy: 1
files:
  - source: /config/locales/en.yml
    translation: /src/locales/%two_letters_code%.yml
    translation_replace:
      zh: zh-CN
      ja: ja-JP
    update_option: update_as_unapproved
pull_request_title: 'fix: new Crowdin translations'
pull_request_labels:
  - Crowdin
commit_message: 'fix: new %language% translations for %original_file_name% from Crowdin'
pull_request_assignees:
  - anushka123123456789
